SET SERVEROUTPUT ON;

CREATE OR REPLACE FUNCTION HAY_CONCIERTO 
(V_F IN DATE) RETURN VARCHAR2(2)
AS
	R VARCHAR2(2);
	V CONCIERTOS.ID_CONCIERTO%TYPE;
BEGIN

	SELECT ID_CONCIERTO INTO V FROM ITINERARIO
	WHERE FECHACONCIERTO=V_F;
	
	IF(V IS NULL) THEN
	R:='N';
	ELSE
	R:='S';
	END IF;
	
	RETURN (R);
	
END HAY_CONCIERTO;
/

DECLARE 
RESPUESTA VARCHAR2(2);
BEGIN
RESPUESTA:=HAY_CONCIERTO(TO_DATE( '01-01-2020', 'DD-MM-YYYY'));
DBMS_OUTPUT.PUT_LINE
('EN ESTA FECHA '||RESPUESTA||' HAY CONCIERTO');
END;
/

SET SERVEROUTPUT ON;
CREATE OR REPLACE FUNCTION FECHA_LIVRE_TEMPORADA 
(V_ID IN TEMPORADAS.ID_TEMPORADA%TYPE)
RETURN DATE
AS
	V_FECHA DATE;
	F_INI  DATE;
	F_FIN  DATE;
	V_F  DATE;
BEGIN

	SELECT FECHAINICIO, FECHAFIN INTO F_INI, F_FIN
	FROM TEMPORADAS
	WHERE ID_TEMPORADA=V_ID;

	V_F:=F_INI;
	
	WHILE(V_FECHA<=F_FIN OR V_FECHA IS NULL) LOOP
	
	V_F:=V_F+1;

	SELECT FECHACONCIERTO INTO V_F FROM ITINERARIO WHERE ID_TEMPORADA=V_ID AND FECHACONCIERTO IS NULL;
	
	IF (V_F>F_INI AND V_F<F_FIN) THEN
		V_FECHA:=V_F;
	END IF;
	
	END LOOP;
	
	RETURN (V_FECHA);
	
END FECHA_LIVRE_TEMPORADA;
/

DECLARE 
V_FECHA DATE;
BEGIN
V_FECHA:=FECHA_LIVRE_TEMPORADA(2);
DBMS_OUTPUT.PUT_LINE('EN LA TEMPORADA HAY UNA FECHA LIVRE EL '||V_FECHA);
END;
/

