CREATE OR REPLACE TRIGGER FECHACONCIERTO_ITINERARIO
BEFORE INSERT OR UPDATE OF ID_CONCIERTO ON ITINERARIO
FOR EACH ROW
DECLARE
	V_ID_TEMPORADA		TEMPORADAS.ID_TEMPORADA%TYPE;
	V_FECHAINICIO		TEMPORADAS.FECHAINICIO%TYPE;
	V_FECHAFIN		TEMPORADAS.FECHAFIN%TYPE;
	V_FECHACONCIERTO 	ITINERARIO.FECHACONCIERTO%TYPE;
	V_ID_CONCIERTO		CONCIERTOS.ID_CONCIERTO%TYPE;
	
BEGIN
	V_ID_CONCIERTO:=:OLD.ID_CONCIERTO;
	V_ID_TEMPORADA:=:OLD.ID_TEMPORADA;

	SELECT FECHACONCIERTO
	INTO V_FECHACONCIERTO
	FROM ITINERARIO
	WHERE ID_CONCIERTO=V_ID_CONCIERTO;
	
	SELECT FECHAINICIO
	INTO V_FECHAINICIO
	FROM TEMPORADAS
	WHERE ID_TEMPORADA=V_ID_TEMPORADA;
	
	SELECT FECHAFIN
	INTO V_FECHAFIN
	FROM TEMPORADAS
	WHERE ID_TEMPORADA=V_ID_TEMPORADA;
	
	IF (V_FECHACONCIERTO<V_FECHAINICIO OR V_FECHACONCIERTO>V_FECHAFIN) THEN
		RAISE_APPLICATION_ERROR(-20000,
		'LA FECHA DEL CONCIERTO NO CORRESPONDE CON LAS FEHCAS LIMITES DE LA TEMPORADA');
	END IF;
END;
/
INSERT INTO Itinerario VALUES (3, 2, TO_DATE ('01-02-2022', 'DD-MM-YYYY'));

CREATE OR REPLACE TRIGGER DIRECTOR_TITULAR_INVITADO
BEFORE INSERT OR UPDATE OF ID_DIRECTOR
ON DIRECTORESINVITADOS
FOR EACH ROW

DECLARE
	V_ID_DIRECTOR				INTÉRPRETES.ID_INTÉRPRETE%TYPE;
	V_ID_DIRECTOR2				INTÉRPRETES.ID_INTÉRPRETE%TYPE;

BEGIN
	V_ID_DIRECTOR:=:OLD.ID_DIRECTOR;
	V_ID_INTERPRETE:=:OLD.ID_INTERPRETE;

	SELECT ID_DIRECTOR
	FROM TITULARES
	INTO 	V_ID_DIRECTOR2
	WHERE  ID_INTERPRETE=V_ID_INTERPRETE;
	
	IF (V_ID_DIRECTOR=V_ID_DIRECTOR2 ) THEN
		RAISE_APPLICATION_ERROR(-20001,'UN DIRECTOR TITULAR NO PUEDE SER INVITADO A SU ORQUESTA');
	END IF;
END;
/

INSERT INTO DirectoresInvitados VALUES (1,1,1);
