CREATE OR REPLACE VIEW VISTA_DIRECTORES_INVITADOS AS	
SELECT 
	D.ID_DIRECTOR, D.NOMBRE AS INVITADO, 
	I.ID_INTÉRPRETE, I.NOMBRE AS ORQUESTA, 
	C.ID_CONCIERTO AS CONCIERTO
FROM DIRECTORES D, INTÉRPRETES I, CONCIERTOS C
WHERE (D.ID_DIRECTOR, I.ID_INTÉRPRETE, C.ID_CONCIERTO) IN 
(SELECT * FROM DIRECTORESINVITADOS)
;

SELECT * FROM VISTA_DIRECTORES_INVITADOS;


CREATE OR REPLACE VIEW VISTA_DIRECTORES_TITULARES AS	
SELECT 
	D.ID_DIRECTOR, D.NOMBRE AS TITULAR, 
	I.ID_INTÉRPRETE, I.NOMBRE AS ORQUESTA, 
	T.ID_TEMPORADA, T.FECHAINICIO || ' - ' || T.FECHAFIN AS TEMPORADA
FROM DIRECTORES D, INTÉRPRETES I, TEMPORADAS T
WHERE (D.ID_DIRECTOR, I.ID_INTÉRPRETE, T.ID_TEMPORADA) IN 
(SELECT * FROM TITULARES)
;

SELECT * FROM VISTA_DIRECTORES_TITULARES;


CREATE OR REPLACE VIEW VISTA_EJECUCIONES AS
SELECT
	O.ID_OBRA, O.TITULO AS OBRA,
	C.ID_CONCIERTO, C.NOMBRE AS CONCIERTO,
	I.ID_INTÉRPRETE, I.NOMBRE AS INTÉRPRETE
FROM OBRAS O, CONCIERTOS C, INTÉRPRETES I
WHERE (O.ID_OBRA, C.ID_CONCIERTO, I.ID_INTÉRPRETE) IN
(SELECT * FROM EJECUCIONES)
;

SELECT * FROM VISTA_EJECUCIONES;

CREATE OR REPLACE VIEW SOLISTAS AS
	SELECT ID_INTÉRPRETE, NOMBRE, FECHANACIMIENTO, INSTRUMENTO
	FROM INTÉRPRETES
	WHERE TIPO='Solista'
;

SELECT * FROM SOLISTAS;

CREATE OR REPLACE VIEW ORQUESTAS AS
	SELECT ID_INTÉRPRETE, NOMBRE, FECHANACIMIENTO, DIRECCIÓN, 
	COMPONENTES
	FROM INTÉRPRETES
	WHERE TIPO='Orquesta'
;

SELECT * FROM ORQUESTAS;

CREATE OR REPLACE VIEW VISTA_OBRAS_CONCIERTOS AS
SELECT
	O.ID_OBRA, O.TITULO AS OBRA,
	C.ID_CONCIERTO, C.NOMBRE AS CONCIERTO
FROM OBRAS O, CONCIERTOS C
WHERE (O.ID_OBRA, C.ID_CONCIERTO) IN
(SELECT ID_OBRA, ID_CONCIERTO FROM EJECUCIONES)
;

SELECT * FROM VISTA_OBRAS_CONCIERTOS;

CREATE OR REPLACE VIEW VISTA_OBRAS_INTÉRPRETES AS
SELECT
	O.ID_OBRA, O.TITULO AS OBRA,
	I.ID_INTÉRPRETE, I.NOMBRE AS INTÉRPRETE
FROM OBRAS O, INTÉRPRETES I
WHERE (O.ID_OBRA, I.ID_INTÉRPRETE) IN
(SELECT ID_OBRA, ID_INTÉRPRETE FROM EJECUCIONES)
;

SELECT * FROM VISTA_OBRAS_INTÉRPRETES;

