CREATE TABLE PROVINCIAS (
	PROVINCIA VARCHAR2(25) PRIMARY KEY,
	DESCRIPCION VARCHAR2(40),
	PREFIJO NUMBER(3)
);

INSERT INTO PROVINCIAS VALUES ('MADRID','CENTRO DEL PAIS',111);
INSERT INTO PROVINCIAS VALUES ('GRANADA','AL SUR Y CON UN POCO DE COSTA',222);
INSERT INTO PROVINCIAS VALUES ('BILBAO','AL NORTE Y SIEMPRE LLUEVE',333);
INSERT INTO PROVINCIAS VALUES ('VALENCIA','A TOPE DE PAELLA',444);
INSERT INTO PROVINCIAS VALUES ('GIRONA','BUENA BUTIFARRA',555);
INSERT INTO PROVINCIAS VALUES ('SALAMANCA','CIUDAD UNIVERSITARIA',666);
INSERT INTO PROVINCIAS VALUES ('TOLEDO','POR DONDE PASA EL TAJO',777);
INSERT INTO PROVINCIAS VALUES ('SORIA','BUENOS TORREZNOS',888);
